spring:
  application:
    name:project
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/job-portal
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
  #Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: JobApplication
    description: Job application by ..
    version: 1.0.0

server:
  port: 9000